import Head from "next/head";
import React from "react";
import styles from "@/styles/component/Layout.module.scss";
import Nav from "@/component/Nav";
import LoginForm from "@/component/LoginForm";

export default function Layout(props : { children: React.ReactNode }) {
    return (
        <>
        <Head>
            <title>PlanIt PokerStar</title>
            <meta name="description" content="Generated by create next app" />
            <script src="https://kit.fontawesome.com/f7632788f8.js" crossOrigin="anonymous"></script>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <Nav/>
            {props.children}
        </main>
        </>
    )
}